wandb_version: 1

model:
  desc: null
  value: cycle_gan
name:
  desc: null
  value: eu2rwa_cycleganFreeze
input_nc:
  desc: null
  value: 3
output_nc:
  desc: null
  value: 3
ngf:
  desc: null
  value: 64
ndf:
  desc: null
  value: 64
netG:
  desc: null
  value: resnet_9blocks
netD:
  desc: null
  value: basic
n_layers_D:
  desc: null
  value: 3
norm:
  desc: null
  value: instance
windows_size:
  desc: null
  value: 100
direction:
  desc: null
  value: AtoB
no_dropout:
  desc: null
  value: true
init_type:
  desc: null
  value: normal
init_gain:
  desc: null
  value: 0.02
epoch:
  desc: null
  value: latest
load_iter:
  desc: null
  value: 0
isTrain:
  desc: null
  value: true
gpu_ids:
  desc: null
  value:
  - 0
preprocess:
  desc: null
  value: null
continue_train:
  desc: null
  value: true
gan_mode:
  desc: null
  value: lsgan
pool_size:
  desc: null
  value: 50
beta1:
  desc: null
  value: 0.5
lambda_identity:
  desc: null
  value: 0.5
lr:
  desc: null
  value: 0.0002
dataset_mode:
  desc: null
  value: unaligned
verbose:
  desc: null
  value: false
lr_policy:
  desc: null
  value: linear
epoch_count:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 200
n_epochs_decay:
  desc: null
  value: 200
lambda_A:
  desc: null
  value: 10.0
lambda_B:
  desc: null
  value: 10.0
lambda_consistencyB:
  desc: null
  value: 10000.0
lambda_popB:
  desc: null
  value: 100.0
display_id:
  desc: null
  value: 1
no_html:
  desc: null
  value: false
display_port:
  desc: null
  value: 8097
use_wandb:
  desc: null
  value: true
display_ncols:
  desc: null
  value: 4
wandb_project_name:
  desc: null
  value: CycleGAN-and-pix2pix
display_winsize:
  desc: null
  value: 100
display_env:
  desc: null
  value: main
display_server:
  desc: null
  value: http://localhost
checkpoints_dir:
  desc: null
  value: /scratch2/metzgern/HAC/code/CycleGANAugs/pytorch-CycleGAN-and-pix2pix/checkpoints/
_wandb:
  desc: null
  value:
    code_path: code/run_train.py
    python_version: 3.10.6
    cli_version: 0.14.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688730594.991699
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.10.6
      5: 0.14.1
      8:
      - 5
      9:
        2: CycleGAN-and-pix2pix
